### ISSUE TITLE
Page header

### ISSUE THREAD

**Issue by e-zim** [hack4impact-calpoly/hack4impact-website#25]
the block at the top of each page. there are two kinds. one has a blurb on left and image on right. one has content then an image under. the screenshots will show.

![Screen Shot 2021-08-20 at 02 11 37](https://user-images.githubusercontent.com/18134219/130210323-c9f11f16-957e-4e2e-967c-bfd5050f41ef.png)
^ this is the _split_ type

![Screen Shot 2021-08-20 at 02 11 48](https://user-images.githubusercontent.com/18134219/130210352-d25a619c-c131-4be2-8584-466b506b7238.png)
^ this is the _full_ type _*see comment for details regarding photo_

Acceptance criteria

- [ ] matches the screenshot

Props to include
```
type: "split" | "full"
title: string
blurb: string
button?: { text: string, link: string }
```

Notes

- may be hard to see, but include the blue blob behind icons

**Comment by Zimboboys** [comment]
update: leave the photo out of the `full` type! this is worthy of it's own component

**Comment by Zimboboys** [comment]
only the header with illustration should be included as a page header. the other type is a combination of normal html
